# Generated by Django 3.2.22 on 2023-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='testfield',
            field=models.CharField(default='foo', max_length=255),
        ),
    ]
