# Generated by Django 3.2.22 on 2023-10-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
