# Generated by Django 3.2.22 on 2023-10-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='testfield',
        ),
    ]
