# Generated by Django 3.2.22 on 2023-10-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipeId',
            new_name='recipe',
        ),
    ]
